### ISSUE TITLE
Chunkwm formula has been removed

### ISSUE THREAD

**Issue by Feirlane** [koekeishiya/homebrew-formulae#13]
Commit [cdba4c0](https://github.com/koekeishiya/homebrew-formulae/commit/cdba4c010620a80bdbbc0fa5c8d3c22b0769ba01) has removed the [chunkwm.rb formula](https://github.com/koekeishiya/homebrew-formulae/commit/cdba4c010620a80bdbbc0fa5c8d3c22b0769ba01#diff-b0fd5ee80d8d270f1ce8274fa17f4298). Was this intentional? 

How should we install chunkwm from brew now? The [user guide](https://koekeishiya.github.io/chunkwm/docs/userguide.html) still mentions this tap as the way to install chunkwm.

**Comment by arames** [comment]
I am wondering the same thing.

I forked this repository and reverted the commit that removed this. So instead of `brew tap koekeishiya/formulae`, you can use my fork with `brew tap arames/homebrew-formulae`.

I recommend checking back here regularly to switch back to this tap, as I won't be maintaining the fork.

**Comment by koekeishiya** [comment]
I no longer maintain chunkwm and I don't want people to install it. If for some reason you want it anyway, you can follow the build instructions on the webpage.

**Comment by arames** [comment]
Oh ok. I had not noticed the line on the chunkwm website (https://koekeishiya.github.io/chunkwm/).

For reference for people coming here, it says "chunkwm is no longer in development because of a C99 re-write, yabai.".
The link to `yabai` is https://github.com/koekeishiya/yabai.

I will definitely try `yabai` when I get time! Thanks for `chunkwm`, and best of luck for `yabai`.

**Comment by ahmadassaf** [comment]
I think there is a big difference between not maintaining an OS service vs. "forcing" people to switch. 

There is no harm in archiving and dropping support for chunkwm but removing the ability for people to install it blocked me at least. I am not ready to move to yabai and I don't even see myself doing that. I have lots of custom scripts made, and cant live with `monocle` amongst other things.

I appreciate all your hard work but I've been messing about building chunkwm for a while now and this is all wasted effort.

**Comment by koekeishiya** [comment]
Building from source is literally running `make install` from a couple of different directories; one for chunkwm-core, one for chunkc, and one for each of the desired plugins: https://koekeishiya.github.io/chunkwm/docs/source.html

I don't consider it my responsibility to provide brew formulas for projects that I no longer work on.
I also cannot promise that the repository will not be deleted at some point in the future if I ever feel like cleaning away old (and irrelevant) codebases. If you are using, and are going to use chunkwm in the future, you should create a fork now. The entire repo is under the MIT license, so go nuts.

It's been roughly 10months since I stopped working on chunkwm, and it's been officially deprecated for about 8months.
